name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 17.2
        uses: actions/setup-java@v3
        with:
          java-version: '17.2'
          distribution: 'temurin'

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Pedidos service
        run: |
          cd prueba/pedidos
          docker build -f java/main/Dockerfile -t $REGISTRY/${REPOSITORY}/pedidos:latest .

      - name: Build Docker image for Productos service
        run: |
          cd prueba/productos
          docker build -f java/main/Dockerfile -t $REGISTRY/${REPOSITORY}/productos:latest .

      - name: Push Docker images to the registry
        run: |
          docker push $REGISTRY/${REPOSITORY}/pedidos:latest
          docker push $REGISTRY/${REPOSITORY}/productos:latest
